=== neeraj19a/Quikr/src/main/resources/TestData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="data" type="dataType"/>
  <xs:complexType name="testDataType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
          </xs:restriction>
        </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="dataType">
    <xs:sequence>
      <xs:element type="testDataType" name="testData" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/quikrX/QuikrXTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../main/resources/TestData.xsd">

    <testData name="CitySelect">mumbai</testData>
    <testData name="cityUrl">mumbai</testData>
    <testData name="newUiCity">bangalore</testData>
    <testData name="myQuikrUrl">MyQuikr</testData>
    <testData name="cityName">bangalore</testData>
    <testData name="CitySelectUrl">http://bangalore.quikr.com/</testData>
    <testData name="expectedPageTitle">Buy Mobile Phones -s- |Secondhand Mobiles for Sale | New Cell Phone Ads in -s- by Quikr</testData>
    <testData name="loginEmail">myordersinteg@test.com</testData>
    <testData name="loginEmailProd">quikrxuser1@gmail.com</testData>
    <testData name="loginEmailE2e">checkoutpagetestuser@test.com</testData>
    <testData name="loginpassword">password</testData>
    <testData name="brandName">Samsung</testData>
    <testData name="mvpCityUrl">http://vasaivirar.quikr.com/</testData>
    <testData name="operatingSystem">Android</testData>
    <testData name="noOfSims">Single SIM</testData>
    <testData name="noOfSimsForExchange">Dual SIM</testData>
    <testData name="screenSize">5 Inches</testData>
    <testData name="primaryCamera">8 MP</testData>
    <testData name="ramValue">2 GB</testData>
    <testData name="processorValue">1 GHz</testData>
    <testData name="searchQueryForPremiumAd">Samsung</testData>
    <testData name="phoneBrandName">Apple</testData>
    <testData name="phoneModelName">iPhone 3G 16 GB</testData>
    <testData name="phoneModelName2">iPhone 3GS 16 GB</testData>
    <testData name="phoneModelName3">iPhone 6 Plus 64 GB</testData>
    <testData name="higherPricePhoneBrandName">Apple</testData>
    <testData name="higherPricePhoneModelName">iPhone 6 16 GB</testData>
    <testData name="signInEmail">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="fullName">Test User</testData>
    <testData name="pinCode">400013</testData>
    <testData name="address">Test Address for QuikrX Order kindly don't confirm this order</testData>
    <testData name="phoneNumber">9987320159</testData>
    <testData name="expectedSortAsecURL">order=priceAsc</testData>
    <testData name="sortOrder">Price: Low to high</testData>
    <testData name="brandNameFilterPageTitle">brand_name</testData>
    <testData name="operatingSystemPageTitle">operating_system</testData>
    <testData name="noOfSimsPageTitle">no_of_sims</testData>
    <testData name="screenSizePageTitle">screen_size</testData>
    <testData name="primaryCameraPageTitle">primary_camera</testData>
    <testData name="ramPageTitle">ram</testData>
    <testData name="processorPageTitle">processor</testData>
    <testData name="searchPageTitle">samsung</testData>
    <testData name="logoutPageTitle">bye</testData>
    <testData name="snbMobilePage">Mobile-Phones</testData>
    <testData name="sortOrderHighestPrice">Price: High to low</testData>
    <testData name="expectedSortDescURL">order=priceDesc</testData>
    <testData name="expectedUnboxedToolTip">Unboxed means that original box containing the phone was opened. Since the seal was broken, manufacturers or retailers could not sell them. The package seal was probably broken for reasons such as wrong model dispatched, seller or customer had to check the package contents etc.</testData>
    <testData name="expectedTrustedSellerToolTip">This device is sold by a Quikr Trusted Seller.</testData>
    <testData name="expectedquikrCertifiedToolTip">We ran a number of tests before putting this device up for sale. This device is Quikr Certified.</testData>
    <testData name="validPinCode">560016</testData>
    <testData name="invalidPinCode">60028</testData>
    <testData name="cartpriceLow1">-Congratulations, we just dropped the &lt; -s- &gt; price from Rs.</testData>
    <testData name="cartpriceLow2">to Rs. </testData>
    <testData name="cartpriceLow3">and you saved Rs. </testData>
    <testData name="cartpriceHigh1">-Ooops... Looks like the &lt; -s- &gt; price has increased from Rs.</testData>
    <testData name="cartpriceHigh2">to Rs. </testData>
    <testData name="cartpriceHigh3">since you last checked</testData>
    <testData name="cartOos1">-Ooops... Looks like the &lt; -s- &gt; has gone out of stock. We have modified your cart, you may continue shopping with </testData>
    <testData name="cartOos2"> more sellers.</testData>
    <testData name="checkOutpricelow">*Price dropped since you last checked</testData>
    <testData name="checkOutpriceHigh">*Price increased since you last checked</testData>
    <testData name="checkOutOutOfStock1">Seller Out of Stock </testData>
    <testData name="checkOutOutOfStock2">Check Availability with</testData>
    <testData name="checkOutOutOfStock3"> more sellers</testData>
    <testData name="expectedPageTitleForErode">Buy New Mobile Phones -s- | Exchange Mobile Phones</testData>
    <testData name="priceUrl">http://-s-.quikr.com/Apple-iPhone-4S-16-GB-W0QQProdIdZ</testData>
    <testData name="newUiLink">http://-s-.quikr.com/QuikrX/Micromax-Canvas-2-W0QQProdIdZ</testData>
    <testData name="homeUrl">http://-s-.quikr.com/</testData>
    <testData name="sellerId">1006</testData>
    <testData name="item1">     </testData>
    <testData name="item2">1054</testData>
    <testData name="oldPrice">2342</testData>
    <testData name="newPrice1">4325</testData>
    <testData name="newPrice2">2000</testData>
    <testData name="sellerLoginEmail">charabudlakkk@gmail.com</testData>
    <testData name="sellerLoginPassword">swadesh123</testData>
    <testData name="qaSellerUserName">testuser999@test.com</testData>
    <testData name="qaSellerPassword">password</testData>
    <testData name="qaSellerDashBoard">http://qa.seller.com/login</testData>
    <testData name="devSellerDashBoard">http://devseller.com/login</testData>
    <testData name="uatSellerDashBoard">http://seller.quikr.com</testData>
    <testData name="confirmedState">Your order has been confirmed!</testData>
    <testData name="placedState">Your order has been placed!</testData>
    <testData name="cancelledState">Your order has been cancelled!</testData>
    <testData name="dispatchedState">Your order has been dispatched!</testData>
    <testData name="deliveredState">Your order has been delivered!</testData>
    <testData name="sellerName">Rocket Kommerce LLP</testData>
    <testData name="succCode">succCode</testData>
    <testData name="ewItem">1503</testData>
    <testData name="discountItem">1140</testData>
    <testData name="cartLoginEmail">carttestuser@test.com</testData>
    <testData name="detailspageloginemail">detailspagetestuser@test.com</testData>
    <testData name="checkoutpageLoginEmail">checkoutpagetestuser@test.com</testData>
    <testData name="qomaDev">http://quikrexchangeadmin.com/authenticate</testData>
    <testData name="qomaQa">http://qa.qoma.com</testData>
    <testData name="exchangeItemBrand">Xolo</testData>
    <testData name="exchangeItemModel">A500 S</testData>
    <testData name="packSlip">Packslip printed</testData>
    <testData name="manifestGen">Manifestslip Generated</testData>
    <testData name="dispatched">Dispatched</testData>
    <testData name="delivered">Delivered</testData>
    <testData name="alertSuccessMessage">Thank you. We will get back to you once suggested product will be available.</testData>
    <testData name="pincodeSuccess">Yes, we deliver here</testData>
    <testData name="pincodeNA">We don't deliver here</testData>
    <testData name="pincodeNoDelivery">323232</testData>
    <testData name="invalidPincodeMsg">Invalid pincode</testData>
    <testData name="callUsPhone">Call us at 080-67364545 ext 2</testData>
    <testData name="mailUsCerti">Mail us at certified@quikr.com</testData>
    <testData name="mailUsExc">Mail us at exchange@quikr.com</testData>
    <testData name="pinCodeToolTip">Enter your pincode</testData>
    <testData name="paymentRecieved">Payment received by Quikr</testData>
    <testData name="replaceRequest">Replacement request initiated</testData>
    <testData name="recievedByQc">Old SKU recieved by QC</testData>
    <testData name="qcFailed">Old SKU QC failed</testData>
    <testData name="qcPassed">Old SKU QC passed</testData>
    <testData name="seller">Seller</testData>
    <testData name="quikr">Quikr</testData>
    <testData name="certCategory">Quikr Certified</testData>
    <testData name="exchCategory">Brand New Phone</testData>
    <testData name="certDelivery">3 to 5 Days</testData>
    <testData name="exchDelivery">4 to 8 Days</testData>
    <testData name="checkListToolTip">Quikr Certified Pre-owned phone is inspected by our team of engineers. Post inspection the phone is restored to its working condition.</testData>
    <testData name="quikrXhomeUrl">http://-s-.quikr.com/QuikrX/Exchange-Mobile-Phones/w227</testData>
    <testData name="checkOutSingleooS">All our sellers have gone out of stock on this product, please Continue Shopping</testData>
    <testData name="roundCudeEmail">monetizationweb1@mail.quikrtest.com</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/android/alert/AlertTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="MyAlerts">Alerts and Recommended</testData>
    <testData name="email">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="location">Adugodi</testData>
    <testData name="cars">Cars &amp; Bikes</testData>
    <testData name="car">Cars</testData>
    <testData name="price">500000</testData>
    <testData name="brand">Chevrolet</testData>
    <testData name="model">Beat</testData>
    <testData name="variant">1.1 SLX</testData>
    <testData name="year">2002</testData>
    <testData name="distance">25000</testData>
    <testData name="color">Red</testData>
    <testData name="fuel">Diesel</testData>
    <testData name="owner">One</testData>
    <testData name="name">manav dayal</testData>
    <testData name="number">9955199187</testData>
    <testData name="Fuel">Fuel</testData>
    <testData name="createAlert">Create Alert</testData>
    <testData name="MyAccount">My Account</testData>
    <testData name="brand1">Ashok Leyland</testData>
    <testData name="year1">2000</testData>
    <testData name="modelScroll">Year</testData>
    <testData name="yearScrool">Color</testData>
    <testData name="location2">Abhay</testData>
    <testData name="locality">Abhay Reddy Layout</testData>
    <testData name="searchText">samsung mobile</testData>
    <testData name="alert">My Alerts</testData>
    <testData name="mumbaiLocality">Agripada</testData>
    <testData name="cityName">Bangalore</testData>
    <testData name="services">Services</testData>
    <testData name="servicesSubCAt">Airline</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/education/educationHome/EducationHomeTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="selectedCity">bangalore</testData>
    <testData name="changecity">lucknow</testData>
    <testData name="validUrl">.com</testData>
    <testData name="recommendedforyoutext">Recommended for You</testData>
    <testData name="vappagetext">Product Details</testData>

    <testData name="viewadd_text">Description</testData>
    <testData name="convertpremiumad_text">Convert your Ad to a Premium Ad now!</testData>
    <testData name="edityourad_text">Edit Your Ad</testData>
    <testData name="deletead_text">Why do you wish to delete this Ad?</testData>
    <testData name="DownloadAppState">Tamil Nadu</testData>
    <testData name="DownloadAppCity">aarani</testData>
    <testData name="homepageBannerIframeId">google_ads_iframe_/81214979/Desktop_HP_978X125_0</testData>
    <testData name="English">English</testData>


    <testData name="PostAdPageHeadertext">Post Free Ad</testData>
    <testData name="facebookemail">automation.quikr@gmail.com</testData>
    <testData name="facebookpassword">quikr1234</testData>

    <testData name="signupcity">Bangalore</testData>

    <testData name ="cityAgnosticSearchQueryAnotherCityName">Delhi</testData>
    <testData name ="cityAgnosticSearchQueryLocalityName">Panaji</testData>
    <testData name ="cityAgnosticSearchQueryAnotherLocalityName">Rajendranagar</testData>

    <testData name ="DashboardURL">MyQuikr</testData>
    <testData name ="myQuikrChats">MyQuikr?action=mychats</testData>

    <testData name ="cookieName">abRand</testData>
    <testData name ="cookieValue">40</testData>
</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/monetization/MonetizationTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../main/resources/TestData.xsd">

    <testData name="XXX">XXYY</testData>
    <testData name="city">Bangalore</testData>
    <testData name="cityUrl">bangalore</testData>
    <testData name="responsiveHPCity">Pune</testData>
    <testData name="responsiveHPCityURL">pune</testData>
    <testData name="validURL">.com</testData>
    <testData name="category">Mobiles &amp; Tablets</testData>
    <testData name="subCategory">Mobile Phones</testData>
    <testData name="adTitle">THATS HELLUVA TITLE BOSS</testData>
    <testData name="adProductPrice">1000</testData>
    <testData name="address">Testing Address- 123</testData>
    <testData name="pincode">560034</testData>
    <testData name="adproductReservePrice">500</testData>
    <testData name="brandname">Apple</testData>
    <testData name="model">iPhone 1st Gen 16 GB</testData>
    <testData name="operatingSystem">Apple-iOS</testData>
    <testData name="noOfSims">Apple-iOS</testData>
    <testData name="alsoIncludes">Charger</testData>
    <testData name="prodDescription">The hell and heaven when comes together :P</testData>
    <testData name="nameAdPoster">Son of Zeus</testData>
    <testData name="adGreaterListPrice">1000</testData>
    <testData name="adLowerReservePrice">500</testData>
    <testData name="commonPrice">500</testData>
    <testData name="premiumAdPackageBoth">PREMIUM_BOTH_AD</testData>
    <testData name="premiumAdPaymentByCheque">PREMIUM_PAYMENT_CHEQUE</testData>
    <testData name="upgradeAdToPremiumUrl">upgrade/?adid</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/api/cars/lms/LMSAPITestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../main/resources/TestData.xsd">

    <testData name="lmsUser">saurabh.sharma@quikr.com</testData>
    <testData name="lmsUserforTesting">testingcarapi@quikr.com</testData>
    <testData name="GetPermissionByUserIdroleId">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].roleId</testData>
    <testData name="GetPermissionByUserIdroleName">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].roleName</testData>
    <testData name="GetPermissionByUserIdroleDescription">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].roleDescription</testData>
    <testData name="GetPermissionByUserIdroleType">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].roleType</testData>
    <testData name="GetPermissionByUserIdpermissionId">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].lmsPermissions[0].permissionId</testData>
    <testData name="GetPermissionByUserIdpermissionType">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].lmsPermissions[0].permissionType</testData>
    <testData name="GetPermissionByUserIdpermissionTypeValue">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].lmsPermissions[0].permissionTypeValue</testData>
    <testData name="GetPermissionByUserIdpermissionDescription">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].lmsPermissions[0].permissionDescription</testData>
    <testData name="GetPermissionByUserIdpermissionTypeValueString">GetPermissionsByUserIdResponse.GetPermissionsByUserIdData.lmsRoles[0].lmsPermissions[0].permissionTypeValueString</testData>
    <testData name="GetBulkCreatePermissionsResponseStatus">BulkCreatePermissionsResponse.BulkCreatePermissionsData.status</testData>


</data>
