=== neeraj19a/Quikr/src/main/resources/TestData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="data" type="dataType"/>
  <xs:complexType name="testDataType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
          </xs:restriction>
        </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="dataType">
    <xs:sequence>
      <xs:element type="testDataType" name="testData" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/ios/alerts/AlertsTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="cityName">Bangalore</testData>
    <testData name="categoryName">Mobiles</testData>
    <testData name="categoryValue">Mobiles &amp; Tablets</testData>
    <testData name="subCategoryName">mobilePhones</testData>
    <testData name="youRTypeName">individual</testData>
    <testData name="conditionTypeName">used</testData>
    <testData name="brandNameOptionForMobilesCategory">brandNameOptionForMobilesCategory</testData>
    <testData name="email">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="brandName">Brand Name</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/escrow/escrowEndToEnd/EscrowEndToEndTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <!--<testData name="city">bangalore</testData>-->
    <!--<testData name="cityUrl">bangalore</testData>-->
    <!--<testData name="loginEmail">automation.quikr@gmail.com</testData>-->
    <!--<testData name="loginpassword">quikr1234</testData>-->
    <!--<testData name="pap">post-classifieds-ads</testData>-->
    <!--<testData name="category">Home &#38; Lifestyle</testData>-->
    <!--<testData name="home-officefurniture">Home - Office Furniture</testData>-->
    <!--<testData name="adTitle">Test Ad For Automation</testData>-->
    <!--<testData name="price">100000</testData>-->
    <!--<testData name="reversePrice">100000</testData>-->
    <!--<testData name="reversePriceLess">90000</testData>-->
    <!--<testData name="adDescription">Test Description for Test Ad. This is Test Ad for Test Purpose. Posted using test automation</testData>-->
    <!--<testData name="name">Automation User</testData>-->
    <!--<testData name="adSuccessPage">/PostAd/?succeed</testData>-->
    <!--<testData name="searchQuery">Test ad for automation</testData>-->
    <!--<testData name="searchQuery1">Test test</testData>-->
    <!--<testData name="escrowMakeAnOfferPriceLess">80000</testData>-->
    <!--<testData name="escrowMakeAnOfferPriceMore">95000</testData>-->
    <!--<testData name="escrowMakeAnOfferEmail">automation.quikr@gmail.com</testData>-->
    <!--<testData name="escrowMakeAnOfferPhone">9966998855</testData>-->
    <!--<testData name="escrowPaymentPage">/escrowBuyer</testData>-->

    <testData name="categoryMobile">Mobiles &#38; Tablets</testData>
    <testData name="subCatMobile">Mobile Phones</testData>
    <testData name="categoryElectronic">Electronics &#38; Appliances</testData>
    <testData name="subCatElectronic">Laptops - Computers</testData>
    <testData name="categoryHome">Home &#38; Lifestyle</testData>
    <testData name="subCatHome">Home - Office Furniture</testData>
    <testData name="title">Title of an Automation script from Escrow</testData>
    <testData name="price">5000</testData>
    <testData name="minprice">4000</testData>
    <testData name="minpriceandpricesame">5000</testData>
    <testData name="yop">2015</testData>
    <testData name="mobileBrand">Sony</testData>
    <testData name="screenSize">14-14.9 inches</testData>
    <testData name="ramsize">6GB</testData>
    <testData name="furnituretype">Office Chair</testData>
    <testData name="OS">Blackberry</testData>
    <testData name="sims">Dual</testData>
    <testData name="includedItem">Data Cable</testData>
    <testData name="functionalCheck">None</testData>
    <testData name="description">Description of an Automation script from Escrow automation tests</testData>
    <testData name="sellerName">AutomationUser</testData>
    <testData name="sellerMail">web18@mail.quikrtest.com</testData>
    <testData name="sellerMobile">9900887766</testData>
    <testData name="sellerAddress">Some Address</testData>
    <testData name="sellerCity">Bangalore</testData>
    <testData name="sellerLocality">Agaram</testData>
    <testData name="sellerPincode">560001</testData>
    <testData name="counterPrice">4700</testData>
    <testData name="buyerName">WebTwenty</testData>
    <testData name="buyerMail">web20@mail.quikrtest.com</testData>
    <testData name="buyerPassword">quikr123</testData>
    <testData name="buyerMobile">9800987676</testData>
    <testData name="buyerCity">Bangalore</testData>
    <testData name="buyerAddress">Thanisandra</testData>
    <testData name="buyerPincode">560077</testData>
    <testData name="priceMAO">4500</testData>
    <testData name="searchBrandName">Apple</testData>

    <testData name="cardType">debit</testData>
    <!--testData name="cardNo">4012001037141112</testData-->
    <testData name="cardNo">5555555555554444</testData>
    <testData name="expiryDate">72020</testData>
    <testData name="cvv">123</testData>

    <testData name="sellerNameProd">ProdSeller</testData>
    <testData name="sellerMailProd">qkrseller@gmail.com</testData>
    <testData name="sellerMobileProd">9972199782</testData>
    <testData name="sellerAddressProd">Seller Address</testData>
    <testData name="sellerCityProd">Bangalore</testData>
    <testData name="sellerLocalityProd">Electronics City</testData>
    <testData name="sellerPincodeProd">560100</testData>
    <testData name="counterPriceProd">4700</testData>
    <testData name="buyerNameProd">ProdBuyer</testData>
    <testData name="buyerMailProd">qkrbuyer@gmail.com</testData>
    <testData name="buyerMobileProd">9972198681</testData>
    <testData name="buyerCityProd">Bangalore</testData>
    <testData name="priceMAOElect">9000</testData>
    <testData name="priceMAOElect1">10000</testData>
    <testData name="priceMAOHome">3000</testData>
    <testData name="priceMAOHome1">4000</testData>
    <testData name="priceMAOMobile">6000</testData>
    <testData name="priceMAOMobile1">1000</testData>
    <testData name="counterPriceElect">10500</testData>
    <testData name="counterPriceHome">3500</testData>
    <testData name="counterPriceMobile">7000</testData>
    <testData name="counterPriceMobileLessThanOffer">3000</testData>
</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/android/horizontalTests/HorizontalTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">
    <testData name="servicescategory">Services</testData>
    <testData name="servicesadTitle">Looking for a driver job</testData>
    <testData name="servicesadDescription">looking for a driver job, have 3+ yrs experience</testData>
    <testData name="servicessubcategory1">Business Offers</testData>
    <testData name="adType">wantDriver</testData>
    <!-- real estate post ad data-->
    <testData name="realEstatesubCat">Real Estate</testData>
    <testData name="realEstaterent">Houses - Apartments for Rent</testData>
    <testData name="realEstateAdTitle">3 bhk flat on rent</testData>
    <testData name="realEstatedesc">3 month old falt in bangalore in good condition</testData>
    <testData name="realEstateowner">One</testData>
    <testData name="realEstaterooms">3 BHK</testData>
    <testData name="realEstatearea">1500 - 2000</testData>
    <testData name="realEstatefurnished">Semi-Furnished</testData>
    <testData name="realEstatearea">1500</testData>
    <testData name="realEstateSemiFurnished">Semi-Furnished</testData>

<!--jobs post ad data-->
    <testData name="JOBS">Jobs</testData>
    <testData name="jobsfullTimeJobs">Full Time Jobs</testData>
    <testData name="jobsadTitle">post an ad for offer ad or want ad</testData>
    <testData name="jobsadDescription">to check that role field is display for job category</testData>
    <testData name="jobsadTitleForAdPost">Job looking for any profile</testData>
    <testData name="jobsadDescriptionForAdPost">I am a UI Developer and Designer B-Tech Passout  2014 and Looking for Job to settle my career</testData>
    <testData name="jobseducationOptionName">Graduate</testData>
    <testData name="jobsexperienceOptionName">Less than 1 yr</testData>
    <testData name="jobscurrentSalaryOptionName">Rs. 2L - Rs. 5L</testData>
    <testData name="jobsrole">Architect</testData>
    <testData name="nameOfPerson">Akshay raj</testData>

    <!-- cars post ad data-->
    <testData name="AdTitle">Chevrolet car on sale</testData>
    <testData name="desc">Six months old Chevrolet car is on sale</testData>
    <testData name="location">80 Ft. Road</testData>
    <testData name="cars">Cars</testData>
    <testData name="car">Cars</testData>
    <testData name="price">500000</testData>
    <testData name="brand">Chevrolet</testData>
    <testData name="model">Beat</testData>
    <testData name="variant">Diesel</testData>
    <testData name="year">2004</testData>
    <testData name="distance">25000</testData>
    <testData name="color">Red</testData>
    <testData name="fuel">Diesel</testData>
    <testData name="owner">One</testData>
    <testData name="name">rahul singh</testData>
    <testData name="email">automation.quikr@gmail.com</testData>
    <testData name="number">9955199187</testData>
    <testData name="PostAd">Post Your Ad</testData>
    <testData name="modelAssertionString">Please select model</testData>
    <testData name="incompleteAdTitle">cars in</testData>
    <testData name="incompleteDesc">Six months old honda</testData>
    <testData name="MyAds">My Ads</testData>
    <testData name="newLocation">Agaram</testData>
    <testData name="save">Save</testData>
    <testData name="Category">Cars</testData>
    <testData name="bike">Honda</testData>
    <testData name="recentlyViewed">Recently Viewed Ads</testData>
    <testData name="NofikarOptions">Ac/Heater</testData>
    <testData name="priceField">Enter Price</testData>
    <testData name="KiloMeter">Kms Driven</testData>
    <testData name="scrollVAp">Description</testData>
    <testData name="ScrollToPrice">Your contact information</testData>
    <testData name="newName">rahul sharma</testData>
    <testData name="kmDrivenMsp">5000-20000</testData>
    <testData name="AlertBrand">Chevrolet</testData>
    <testData name="city">Ahmedabad</testData>
    <testData name="inspectionreport">Inspection Report</testData>
    <testData name="off">OFF</testData>
    <testData name="bikeBrand">Bajaj</testData>
    <testData name="bikesModel">Discover 125</testData>
    <testData name="commercialVehicles">Commercial Vehicles</testData>
    <testData name="Boat">Boat</testData>
    <testData name="invalidNumber">987</testData>
    <testData name="invalidEmail">guughuj</testData>
    <testData name="invalidNumberMessage">Enter 10 digit mobile number</testData>
    <testData name="invalidEmailMessage">Enter valid email Address</testData>
    <testData name="bikes">Bikes</testData>
    <testData name="otherVehicle">Other Vehicles</testData>
    <testData name="commercialVehicle">Commercial Vehicles</testData>
    <testData name="vehicleType">Vehicle Type</testData>
    <testData name="EditAdTitle">Chevrolet brand car on sale</testData>
    <testData name="SaveAD">Save</testData>
    <testData name="carsAttribute">Enter Kms Driven</testData>
    <testData name="mobilesAttribute">Operating System</testData>
    <testData name="realEstateAttribute">I  want  to  take  on  rent  I  am  a  tenant</testData>

<!--escrow test data-->
    <testData name="escrowmobilesAndTAbs">Mobiles</testData>
    <testData name="price">5000</testData>
    <testData name="escrowemail">automtion.quikr@gmail.com</testData>
    <testData name="escrowmobiles">Mobile Phones</testData>
    <testData name="LowTouchText">Congratulations ! You will now be eligible for upto â‚¹ 1000cashback and FREE pickup when buyer uses "Make an Offer" on your posted ad.</testData>
    <testData name="escrowAdTitle">want to sell my i phone</testData>
    <testData name="escrowDesc">wanted to sell my i phone which is  2 months old</testData>
    <testData name="escrowlocation">80 Ft. Road</testData>
    <testData name="escrowsim">Single</testData>
    <testData name="escrowosType">Apple-iOS</testData>
    <testData name="escrowbrand">Apple</testData>
    <testData name="escrowmodel">iPhone 3 16 GB</testData>
    <testData name="escrowpin">560008</testData>
    <testData name="escrowaddress">jamuna nagar, near ganga river sangam</testData>
    <testData name="escrowPoastAdCat">Electronics </testData>
    <testData name="escrowlaptops">Laptops</testData>
    <testData name="escrowscreenSize">13-13.9 inches</testData>

    <!-- horizontal vap-->
    <testData name="viewProfile">View Profile</testData>
    <testData name="newRole">BPO</testData>
    <testData name="autosuggestsubcat">Houses for Rent</testData>
    <testData name="subcategory">Architect</testData>
    <testData name="email">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="reportAdComment">not satisfied with the details provided </testData>
    <testData name="reportAdSuccessMsg">Thanks for Reporting!</testData>
    <testData name="buyOrSellAnyThing">Buy or Sell anything</testData>
    <testData name="searchAndBrowse">Search</testData>
    <testData name="communicate">Communicate</testData>
    <testData name="quikrNxt">Quikr Nxt</testData>
    <testData name="hydrabad">Hyderabad</testData>
    <testData name="showAllOption">showAllOption</testData>
    <testData name="servicesSearchBar">servicesSearchBar</testData>
    <testData name="similarAds">Similar Ads</testData>


<!--horizontal Snb
-->
    <testData name="mobilesAndTAbs">Mobiles</testData>
    <testData name="Mostrecrent">Most Recent (default)</testData>
    <testData name="nearest">Nearest</testData>
    <testData name="escrowbrand1">ios</testData>
    <testData name="language">Language Settings</testData>
    <testData name="recentlyViewed">Recently Viewed Ads</testData>
    <testData name="samsung">samsung</testData>
    <testData name="Entertainment">Entertainment</testData>
    <testData name="showAllOption">showAllOption</testData>
    <testData name="servicesSearchBar">servicesSearchBar</testData>
    <testData name="SERVICES">Services</testData>
    <testData name="subcategory">Business Offers</testData>
    <testData name="showMoreCategories">More</testData>
    <testData name="MyAccount">My Account</testData>
    <testData name="home">Home</testData>
    <testData name="browseAdsOption">Browse Ads</testData>
    <testData name="cityName">Bangalore</testData>
    <testData name="alert">My Alerts</testData>
    <testData name="lowestPriceFirstSOrt">Lowest Price</testData>
    <testData name="MyChats">My Chats</testData>
    <testData name="selectBrand">Brand Name</testData>
</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/ios/chat/ChatTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="categoryName">Mobiles</testData>
    <testData name="subCategoryName">mobilePhones</testData>
    <testData name="sendText">Hi i am interested</testData>
    <testData name="name">Monu</testData>
    <testData name="emailId">automation.quikr@gmail.com</testData>
    <testData name="mobileNo">9955199187</testData>
    <testData name="password">quikr1234</testData>
    <testData name="wrongEmailId">test@gmail</testData>
    <testData name="uiaTableViewForMcrScreen">uiaTableViewForMcrScreen</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/android/jobs/JobsTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">
    <testData name="jobs">Jobs</testData>
    <testData name="fullTimeJobs">Full Time Jobs</testData>
    <testData name="adTitle">post an ad for offer ad or want ad</testData>
    <testData name="adDescription">to check that role field is display for job category</testData>
    <testData name="locality">80 Ft. Road</testData>
    <testData name="alertsAndRecommendation">Alerts and Recommended</testData>
    <testData name="adTitleForAdPost">Job looking for Architect Job In Bangalore</testData>
    <testData name="adDescriptionForAdPost">I am a civi engineer and Designer  and Looking for Job to settle my career</testData>
    <testData name="educationOptionName">Graduate</testData>
    <testData name="experienceOptionName">Less than 1 yr</testData>
    <testData name="currentSalaryOptionName">Rs. 2L - Rs. 5L</testData>
    <testData name="nameOfPerson">Akshay raj</testData>
    <testData name="mbNumber">9955198856</testData>
    <testData name="adType">Ad Type</testData>
    <testData name="city">Bangalore</testData>
    <testData name="selectRole">Select Role</testData>
    <testData name="selectRoleOptionName">A</testData>
    <testData name="carsAndBikes">Cars</testData>
    <testData name="email">akshayKumar112@gmail.com</testData>
    <testData name="wrongPhoneNo">899999999999</testData>
    <testData name="wrongEmail">abcdf</testData>
    <testData name="name">Mooinou</testData>
    <testData name="salary">0</testData>
    <testData name="inputText">Hi</testData>
    <testData name="NewCity">Delhi</testData>
    <testData name="recentlyViewed">Recently Viewed Ads</testData>
    <testData name="cat">Electronics</testData>
    <testData name="real">Real</testData>
    <testData name="MyAccount">My Account</testData>
    <testData name="RoleExp">3</testData>
    <testData name="languageKnown">English</testData>
    <testData name="educationNew">Graduate</testData>
    <testData name="JOBS">Jobs</testData>
    <testData name="role">Architect</testData>
    <testData name="newRole">BPO</testData>
    <testData name="inddustry">BFSI</testData>
    <testData name="domElementPostAdTextBOx">preFilledData</testData>
    <testData name="RoleField">Role</testData>
    <testData name="jobKeyDomElemnt">SnbJobKEy</testData>
    <testData name="jobVAlueDomelemnt">snbJobVAlue</testData>
    <testData name="jobsSnbHeaderDomElemnt">jobsCreateProfile</testData>
    <testData name="newestFirst">Newest First</testData>
    <testData name="createProfile">Create Free Profile</testData>
    <testData name="filters">Filters</testData>
</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/cars/CarsTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../main/resources/TestData.xsd">

    <testData name="quikrHomePageURL">http://www.quikr.com/</testData>
    <testData name="carsHomePageURL">http://www.quikr.com/Cars-Bikes/</testData>
    <testData name="carsURL">http://www.quikr.com/Cars-Bikes/gId-60</testData>
    <testData name="mobileHomePageURL">http://www.quikr.com/Mobiles-Tablets/</testData>
    <testData name="electronicsHomePageURL">http://www.quikr.com/Electronics-Appliances/</testData>
    <testData name="realEstateHomePageURL">http://www.quikr.com/homes/</testData>
    <testData name="homeLifestyleHomePageURL">http://www.quikr.com/Home-Lifestyle/</testData>
    <testData name="jobsHomePageURL">http://www.quikr.com/Jobs/</testData>
    <testData name="servicesHomePageURL">http://www.quikr.com/Services/</testData>
    <testData name="petsHomePageURL">http://www.quikr.com/Pets-Pet-Care/</testData>
    <testData name="educationHomePageURL">http://www.quikr.com/education-training/</testData>
    <testData name="PAPURL">http://www.quikr.com/post-classifieds-ads/?postadcategoryid</testData>
    <testData name="checkMSPPageURL">http://www.quikr.com/cars-bikes/msp</testData>
    <testData name="newCarsPageURL">http://www.quikr.com/cars/new</testData>

    <testData name="getItInspectedCarsURL">cnInspected</testData>
    <testData name="getItInspectedBikesURL">cnInspected</testData>

    <testData name="dashboardURLCars">http://www.quikr.com/Cars-Bikes/</testData>
    <testData name="dashboardURLHorizontal">http://www.quikr.com/MyQuikr</testData>
    <testData name="myProfileURL">http://www.quikr.com/MyQuikr</testData>
    <testData name="myAdsURL">http://www.quikr.com/MyQuikr?action=activeads</testData>
    <testData name="myAlertsURL">http://www.quikr.com/MyQuikr?action=alertsdetails</testData>
    <testData name="myChatsURL">http://www.quikr.com/MyQuikr?action=mychats</testData>
    <testData name="mySavedAdsURL">MyQuikr?action=mysavedads</testData>
    <testData name="forgotPasswordURL">http://www.quikr.com/ResetPassword</testData>
    <testData name="signupURL">http://www.quikr.com/Register?register=done</testData>
    <testData name="logoutURL">http://www.quikr.com/Cars-Bikes</testData>

    <testData name="carsSNBURL">http://www.quikr.com/Cars/</testData>
    <testData name="bikesScootersSNBURL">http://www.quikr.com/Bikes-Scooters/</testData>
    <testData name="commercialVehiclesSNBURL">http://www.quikr.com/Commercial-Vehicles/</testData>
    <testData name="bicyclesSNBURL">http://www.quikr.com/Bicycles/</testData>
    <testData name="sparePartsNSBURL">http://www.quikr.com/Spare-Parts-Accessories/</testData>
    <testData name="otherSNBURL">http://www.quikr.com/Other-Vehicles/</testData>

    <testData name="aboutUsURL">http://www.quikr.com/html/about.php</testData>
    <testData name="contactUsURL">http://www.quikr.com/html/contact.php</testData>
    <testData name="careersURL">http://www.quikr.com/html/jobs.php</testData>
    <testData name="quikrVideosURL">http://www.quikr.com/video?id=vhS7M5IdOpI</testData>
    <testData name="advertiseURL">http://www.quikr.com/adsales</testData>
    <testData name="blogURL">http://www.quikr.com/cars-bikes/pitstop/</testData>
    <testData name="helpURL">http://www.quikr.com/help/</testData>
    <testData name="iosAppURL">https://itunes.apple.com/in/app/quikr-free-local-classifieds/</testData>
    <testData name="androidAppURL">https://play.google.com/store/apps/details?id=com.quikr</testData>
    <testData name="windowsAppURL">https://www.microsoft.com/en-us/store/apps/quikr-buy-sell/9wzdncrcwnk5</testData>
    <testData name="listingPolicyURL">http://www.quikr.com/html/policies.php</testData>
    <testData name="termsOfUseURL">http://www.quikr.com/html/termsandconditions.php</testData>
    <testData name="privacyPolicyURL">http://www.quikr.com/html/privacy.php</testData>
    <testData name="quikrXPolicyURL">http://www.quikr.com/html/quikrxpolicy.php</testData>

    <testData name="emailId">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="city">Delhi</testData>

    <testData name="cityUrl">delhi</testData>
    <testData name="cityChange">chennai</testData>
    <testData name="searchItem">Hyundai</testData>
    <testData name="resultSearchPage">hyundai-cars/hyundai</testData>
    <testData name="carHomePage">Cars-Bikes</testData>
    <testData name="chatName">testName</testData>
    <testData name="chatNumber">9876543210</testData>
    <testData name="chatEmail">test@aol.com</testData>
    <testData name="chatContent">Hi there</testData>
    <testData name="alertMessage">Great! Your alert has been successfully created</testData>
</data>
