=== neeraj19a/Quikr/src/main/resources/TestData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="data" type="dataType"/>
  <xs:complexType name="testDataType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
          </xs:restriction>
        </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="dataType">
    <xs:sequence>
      <xs:element type="testDataType" name="testData" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/realEstate/RealEstateTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../main/resources/TestData.xsd">

    <testData name="homesHomePageUrl">www.quikr.com/homes</testData>
    <testData name="selectedCity">bangalore</testData>
    <testData name="city">Bangalore</testData>
    <testData name="cityUrl">bangalore</testData>
    <testData name="utmpValue">utmp=Hp?catname=Real-Estate&amp;t72=responsiveUI,v72=True</testData>
    <testData name="analyticsUrl">www.google-analytics.com</testData>
    <testData name="expectedURL">bangalore</testData>
    <testData name="emailId">automation.quikr@gmail.com</testData>
    <testData name="loginpassword">quikr1234</testData>
    <testData name="phoneNumber">9999999999</testData>
    <testData name="CitySelect">Bangalore</testData>
    <testData name="category">Jobs</testData>
    <testData name="subcategory">Full Time Jobs</testData>
    <testData name="wantAd">I am an employer</testData>
    <testData name="offerAd">I am a jobseeker</testData>
    <testData name="education">Graduate</testData>
    <testData name="experience">3 - 5 yrs</testData>
    <testData name="locality">Adugodi</testData>
    <testData name="role">Accountant</testData>
    <testData name="facebookemail">automation.quikr@gmail.com</testData>
    <testData name="facebookpassword">quikr1234</testData>
    <testData name="city">delhi</testData>
    <testData name="ProjectName">test</testData>
    <testData name="area">1234</testData>
    <testData name="price">321</testData>
    <testData name="rate">32</testData>
    <testData name="locality">delhi</testData>
    <testData name="basicinformation_streetaddress">delhi</testData>
    <testData name="propertydetails_floorNumber">1</testData>
    <testData name="propertydetails_date">4</testData>
    <testData name="propertydetails_buildingname">Manyata</testData>
    <testData name="propertydetails_flatnumber">108</testData>
    <testData name="photomedia_adtitle">Ad Title QuikrHomes Flat number 108 Available in Delhi,Bui</testData>
    <testData name="photomedia_addesc">Ad Description Flat is fully furnished all amenities Near By, In Posh locality of Delhi Area, Malls nearby</testData>
    <testData name="postad_message">Thank you for posting your Ad on Quikr Homes</testData>
    <testData name="cookiename">abRand</testData>
    <testData name="quikrhomeNewUIcookie">7</testData>
    <testData name="searchquery">vas</testData>
    <testData name="Bangalorecity">Bangalore</testData>
    <testData name="search_Kormangla">Kor</testData>


    <testData name="cityname">bangalore</testData>

    <!-- Post Ad Page Test Data-->
    <testData name="papcategory">Commercial</testData>
    <testData name="adtype">sell</testData>
    <testData name="papprojectname">Veracious</testData>
    <testData name="papprice">911000000</testData>
    <testData name="adtitle">Residential Apartments/Villa Availble in  Bangalore.Sample</testData>
    <testData name="addesc">Residential Apartments/Villa Availble in  Bangalore.Sample Flats are also available </testData>
    <testData name="radio">individual</testData>
    <testData name="email">quikr@autotest.com</testData>
    <testData name="phone">9742111124</testData>



</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/website/horizontal/pap/PapTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="selectedCity">bangalore</testData>
    <testData name="instituteName">Parivarthan Counselling Training &amp; Research Centre</testData>
    <testData name="instituteWebsite">http://www.parivarthan.org/</testData>
    <testData name="instituteAddress">No. 3310, 1st Floor, 8th Cross, 13th Main, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560008</testData>
    <testData name="quikrUrl">quikr.com</testData>
    <testData name="AdTitleMobilePhones">I want to sell my new sony xperia z10 in good condition.</testData>
    <testData name="AdDescriptionMobilePhones">The phone is in a very good condition. intact with original earphones, charger and battery. You can contact for more.</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/ios/electronicsAndAppliances/ElectronicsAndAppliancesTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="cityName">Bangalore</testData>
    <testData name="cityNameForPostAd">Mumbai</testData>
    <testData name="localityNameForPostAd">Agripada</testData>
    <testData name="categoryName">Electronics</testData>
    <testData name="categoryValue">Electronics &amp; Appliances</testData>
    <testData name="subCategoryName">laptop</testData>
    <testData name="adTitle">i want to sell Acer laptop</testData>
    <testData name="adDescription">Acer laptop in good condition with charger and it was used only 6 months </testData>
    <testData name="youRTypeName">individual</testData>
    <testData name="conditionTypeName">used</testData>
    <testData name="productTypeName">laptop</testData>
    <testData name="priceAmount">50000</testData>
    <testData name="name">Monu</testData>
    <testData name="emailId">automation.quikr@gmail.com</testData>
    <testData name="mobileNo">9955199187</testData>
    <testData name="incompleteAdTitle">title</testData>
    <testData name="incompleteAdDescription">Post ad</testData>
    <testData name="brandNameOptionForElectronicsCategory">brandNameOptionForElectronicsCategory</testData>
    <testData name="alsoIncludesOptionNameForElectronicsCategory">alsoIncludesOptionNameForElectronicsCategory</testData>
    <testData name="successMsgAfterAdPost">We are reviewing your ad.</testData>
    <testData name="pinCode">560066</testData>
    <testData name="address">Quikr india pvt ltd</testData>
    <testData name="mobile">mobile</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/ios/home/HomeTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="expectedCityName">Bangalore</testData>
    <testData name="categoryName">Mobiles</testData>
    <testData name="subCategoryName">mobilePhones</testData>
    <testData name="enterRequiredSearchText">Apple</testData>
    <testData name="changeCityName">selectNameForChangeCity</testData>
    <testData name="city">Delhi</testData>
    <testData name="exchangeOldForNew">exchangeOldForNew</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/ios/quikrX/QuikrXTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="cityName">Bangalore</testData>
    <testData name="categoryName">Mobiles</testData>
    <!--<testData name="categoryValue">Mobiles &amp; Tablets</testData>-->
    <testData name="exchangeOldForNew">exchangeOldForNew</testData>
    <testData name="buyCertifiedUsedPhone">buyCertifiedUsedPhone</testData>
    <testData name="pinCode">560066</testData>
    <testData name="brandNameOptionOnVapPage">brandNameOptionOnVapPage</testData>
    <testData name="modelNameOption">modelNameOption</testData>
    <testData name="emailId">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="userName">Monu</testData>
    <testData name="mobileNo">9955199187</testData>
    <testData name="address">Quikr india pvt ltd near manyta tech park</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/msite/mHorizontal/MHorizontalTestData.xml
<?xml version="1.0"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../main/resources/TestData.xsd">

    <testData name="selectedCity">bangalore</testData>
    <testData name="emailId">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="homepage">quikr.com</testData>
    <testData name="mspURL">msp</testData>
    <testData name="category">Cars &amp; Bikes</testData>
    <testData name="subCategory">Bikes &amp; Scooters</testData>
    <testData name="brand">Bajaj</testData>
    <testData name="mobileBrand">Apple</testData>
    <testData name="mobileModel">iPhone 1st Gen 16 GB</testData>
    <testData name="model">Avenger</testData>
    <testData name="year">2011</testData>
    <testData name="mobile">mobile</testData>
    <testData name="validpage">quikr.com</testData>
    <testData name="LaptopsandComputers">Laptops - Computers</testData>
    <testData name="ComputersandPeripherals">Computer Peripherals</testData>
    <testData name="lowestpricesorttype">Lowest Price</testData>
    <testData name="highestpricesorttype">Highest Price</testData>
    <testData name="mostrecentsorttype">Most Recent (default)</testData>
    <testData name="withpicturesorttype">With Picture</testData>
    <testData name="papPage">post-classifieds-ads</testData>
    <testData name="profileName">Test User</testData>
    <testData name="profilePhNum">8558558526</testData>
    <testData name="selectcategoryURL">select-category</testData>
    <testData name="CategoryCarsandBikes">Cars &amp; Bikes</testData>
    <testData name="CategoryMobilesandTablets">Mobiles &amp; Tablets</testData>
    <testData name="SubCategoryMobiles">Mobile Phones</testData>
    <testData name="CategoryElectronics">Electronics &amp; Appliances</testData>
    <testData name="CategoryRealEstate">Real Estate</testData>
    <testData name="CategoryHomeandLifeStyle">Home &amp; Lifestyle</testData>
    <testData name="CategoryJobs">Jobs</testData>
    <testData name="CategoryEntertainment">Entertainment</testData>
    <testData name="CategoryServices">Services</testData>
    <testData name="SubCategoryCars">Cars</testData>
    <testData name="SetAttributesURL">set-attributes</testData>
    <testData name="CategoryServices">Services</testData>
    <testData name="SubCategoryCars">Cars</testData>
    <testData name="SetAttributesURL">set-attributes</testData>
    <testData name="ValidationMsgPrice">Enter Price</testData>
    <testData name="ValidationMsgBrand">Select Brand Name</testData>
    <testData name="ValidationMsgYear">Select Year</testData>
    <testData name="ValidationMsgKms">Enter Kms Driven</testData>
    <testData name="ValidationMsgCity">Please select city</testData>
    <testData name="Price">15000</testData>
    <testData name="Brand">Audi</testData>
    <testData name="Model">A3</testData>
    <testData name="Variant">35 TDI Attraction</testData>
    <testData name="OperatingSystem">Android</testData>
    <testData name="Year">2011</testData>
    <testData name="Kms">16000</testData>
    <testData name="Color">Black</testData>
    <testData name="Fuel">Petrol</testData>
    <testData name="NoOfOwners">One</testData>
    <testData name="Insurancedate">2</testData>
    <testData name="PostAdURL">post-ad</testData>
    <testData name="ValidationMsgAdDescription">Description Should be minimum 8 words</testData>
    <testData name="ValidationMsgAdDescription1">Invalid Email</testData>
    <testData name="AdDescription">Audi 2011 Model Black Color for Sale, Excellent Condition</testData>
    <testData name="MobilesAdDescription">Mobile is in Great Condition, No Scratch, All accessories with Box</testData>
    <testData name="PostAdSuccessfulURL">succeed</testData>
    <testData name="255PremiumPlan">₹ 374</testData>
    <testData name="300PremiumPlan">₹ 499</testData>
    <testData name="450PremiumPlan">₹ 749</testData>
    <testData name="15daysPremiumPlan">15 days</testData>
    <testData name="1monthPremiumPlan">1 month</testData>
    <testData name="60daysPremiumPlan">60 days</testData>
    <testData name="PaymentGatewayURL">select-payment-gateway</testData>
    <testData name="PaymentMode1">Pay via Mobile Billing</testData>
    <testData name="PaymentMode2">Credit Card / Debit Card</testData>
    <testData name="PaymentMode3">Net Banking</testData>
    <testData name="ProdTypeSnbFilter">Desktop</testData>
    <testData name="alertCreationDesc">description</testData>
    <testData name="alertCreationCars">cars</testData>
    <testData name="CardTypeCredit">credit</testData>
    <testData name="CardTypeDebit">debit</testData>
    <testData name="CardNumberCreditAmericanExpress">378282246310005</testData>
    <testData name="NameofHolder">Automation Quikr</testData>
    <testData name="ExpiryDate">07/21</testData>
    <testData name="CVV">690</testData>
    <testData name="BankName">ICICI Bank</testData>
    <testData name="ICICIBankPaymentPage">shopping.icicibank.com</testData>
    <testData name="ChatMessage">Hi are u there?</testData>
    <testData name="PostAdSuccesfull">PostAd/?succeed</testData>
    <testData name="offerPrice">100000</testData>
    <testData name="JunkMail">junkabc@aol.com</testData>
    <testData name="ques">Where is the party Bro!</testData>
    <testData name="NewUICity">Gurgaon</testData>
    <testData name="Address">Testing Address 1234 567 89 []</testData>
    <testData name="pincode">560032</testData>
    <testData name="postAdTextinHindi">विज्ञापन पोस्ट करें</testData>
    <testData name="postAdTextinTamil">இலவச விளம்பரம் செய்</testData>
    <testData name="postAdTextinTelugu">ఉచిత ప్రకటనను పోస్ట్ చేయండి</testData>
    <testData name="postAdTextinMalyalam">സൌജന്യ പരസ്യം നല്കുക</testData>
    <testData name="postAdTextinKannada">ಉಚಿತ ಜಾಹೀರಾತನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ</testData>
    <testData name="postAdTextinMarathi">जाहिरात पोस्ट करा</testData>
    <testData name="postAdTextinGujarati">મફત જાહેરાત</testData>
    <testData name="MatchingAdsBikes">Bikes-Scooters</testData>
    <testData name="chatName">Testing Name</testData>

</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/android/cars/CarsTestData.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/TestData.xsd">

    <testData name="Appversion">About Quikr</testData>

    <testData name="MyAccount">My Account</testData>
    <testData name="AdTitle">Honda car on sale</testData>
    <testData name="desc">Six months old honda car is on sale</testData>
    <testData name="location">80 Ft. Road</testData>
    <testData name="cars">Cars &amp; Bikes</testData>
    <testData name="car">Cars</testData>
    <testData name="price">500000</testData>
    <testData name="brand">Chevrolet</testData>
    <testData name="model">Beat</testData>
    <testData name="variant">Diesel</testData>
    <testData name="year">2004</testData>
    <testData name="distance">25000</testData>
    <testData name="color">Red</testData>
    <testData name="fuel">Diesel</testData>
    <testData name="owner">One</testData>
    <testData name="name">manav dayal</testData>
    <testData name="email">automation.quikr@gmail.com</testData>
    <testData name="number">9955199187</testData>
    <testData name="PostAd">Post Your Ad</testData>
    <testData name="modelAssertionString">Please select model</testData>
    <testData name="incompleteAdTitle">cars in</testData>
    <testData name="incompleteDesc">Six months old honda</testData>
    <testData name="MyAds">My Ads</testData>
    <testData name="newLocation">Agaram</testData>
    <testData name="save">Save</testData>
    <testData name="Category">Cars</testData>
    <testData name="cranation">CARNATION OVERALL RATING</testData>
    <testData name="bike">Honda</testData>
    <testData name="recentlyViewed">Recently Viewed Ads</testData>
    <testData name="NofikarOptions">Ac/Heater</testData>
    <testData name="priceField">Enter Price</testData>
    <testData name="KiloMeter">Kms Driven</testData>
    <testData name="scrollVAp">Description</testData>
    <testData name="ScrollToPrice">Your contact information</testData>
    <testData name="newName">rahul sharma</testData>
    <testData name="kmDrivenMsp">5000-20000</testData>
    <testData name="AlertBrand">Chevrolet</testData>
    <testData name="city">Ahmedabad</testData>
    <testData name="inspectionreport">Overall Inspection Rating </testData>
    <testData name="off">OFF</testData>
    <testData name="bikeBrand">Bajaj</testData>
    <testData name="bikesModel">Discover 125</testData>
    <testData name="commercialVehicles">Commercial Vehicles</testData>
    <testData name="boat">Boat</testData>
    <testData name="invalidNumber">987</testData>
    <testData name="invalidEmail">guughuj</testData>
    <testData name="invalidNumberMessage">Enter 10 digit mobile number</testData>
    <testData name="invalidEmailMessage">Enter valid email Address</testData>
    <testData name="loginEmail">automation.quikr@gmail.com</testData>
    <testData name="loginPassword">quikr1234</testData>
    <testData name="GetQuotePrefixText">Buy insurance for just</testData>
    <testData name="bikes">Bikes</testData>
    <testData name="otherVehicle">Other Vehicles</testData>
    <testData name="commercialVehicle">Commercial Vehicles</testData>
    <testData name="vehicleType">Vehicle Type</testData>
    <testData name="GetViewNumberVap">View Number</testData>
    <testData name="freeText">ca</testData>
    <testData name="Boat">Boat</testData>
    <testData name="BrandForMsp">Suzuki</testData>
    <testData name="ModelForMSP">Bandit</testData>
    <testData name="FieroModelMsp">Fiero</testData>
    <testData name="getMspResultText">MSP Result</testData>
    <testData name="IamBuying">I'm Buying</testData>
    <testData name="IamSelling">I'm Selling</testData>
    <testData name="NewCarsText">Looking for a specific car?</testData>
    <testData name="AstonMartinTextContains">Aston Martin</testData>
</data>

=== neeraj19a/Quikr/src/test/java/com/quikr/app/android/horizontalTests/errorMessagesMobileLogin/mobileLoginErrorMessages.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../main/resources/TestData.xsd">


    <!-- “Email already registered” or “Mobile already registered” or "“Email and mobile already registered”-->
    <testData name="signUpErrorMsg1">Email already registered</testData>
    <testData name="signUpErrorMsg2">Mobile already registered</testData>
    <testData name="signUpErrorMsg3">Email and mobile already registered</testData>
    <testData name="verifiedEmail">dhirajbothra04@gmail.com</testData>
    <testData name="registeredEmailErrorMsg">This Email is registered with us. Please login. In case you don't remember password, use Forgot Password</testData>
    <testData name="registeredMobileErrorMsg">This mobile is registered with us. Please login through OTP to proceed.</testData>
    <testData name="PostAdCta">Login</testData>
    <testData name="MyAccount">My Account</testData>
    <testData name="email">automation.quikr@gmail.com</testData>
    <testData name="password">quikr1234</testData>
    <testData name="location">Achitnagar</testData>
    <testData name="number">9955199163</testData>
    <testData name="forgotPasswordEmail">qa2.quikr@gmail.com</testData>
    <testData name="name">rahul singh</testData>
    <testData name="unRegisteredNumber">8004487543</testData>
    <!-- services test data-->
    <testData name="servicescategory">Services</testData>
    <testData name="servicesadTitle">Looking for a driver job</testData>
    <testData name="servicesadDescription">looking for a driver job, have 3+ yrs experience</testData>
    <testData name="servicessubcategory1">Movers</testData>
    <testData name="servicesWantTypeAd">I want a business proposal</testData>
    <!--post Ad Common Attributes Across all Categories-->
    <testData name="brand">Samsung</testData>
    <testData name="cars">Cars</testData>
    <testData name="offerType">I  want  to  sell</testData>
    <testData name="WantType">I  want  to  buy</testData>
    <testData name="postAdAsIndividual">Individual</testData>
    <testData name="postAdAs">Individual</testData>
    <testData name="condition">Used</testData>
    <testData name="SelectLocality">Please Select Locality</testData>
    <testData name="enterName">Please Enter Name</testData>
    <testData name="enterMobileNumber">Please Enter Mobile</testData>
    <testData name="enterPrice">Price</testData>
    <testData name="mobileNumber">Mobile</testData>
    <testData name="emailId">Email</testData>
    <testData name="enterAdTitle">Enter Ad title</testData>
    <testData name="enterDescription">Ad Description</testData>
    <testData name="SelectLocality">Locality</testData>
    <testData name="enterName">Name</testData>
    <testData name="wrongpassword">password</testData>


</data>
